export const DESKTOPS_SIZE = 1280;
export const LAPTOPS_SIZE = 1024;
export const TABLETS_SIZE = 768;
export const MOBILE_SIZE = 480;
export const SUPER_SMALL_SIZE = 320;


export const GAP_BETWEEN_PRODUCTS = 16;
export const LAYOUT_PADDING = 25;

// export const DESKTOPS_PRODUCT_SIZE = (DESKTOPS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS * 3)) / 4;
// export const LAPTOPS_PRODUCT_SIZE = (LAPTOPS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS * 2)) / 3;
// export const TABLETS_PRODUCT_SIZE = (TABLETS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS)) / 2;
// export const MOBILE_PRODUCT_SIZE = 360;

export const DEFAULT_PRODUCT_SIZE = (DESKTOPS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS * 3)) / 4;
export const DESKTOPS_PRODUCT_SIZE = (LAPTOPS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS * 2)) / 3;
export const LAPTOPS_PRODUCT_SIZE = (TABLETS_SIZE - (LAYOUT_PADDING * 2 + GAP_BETWEEN_PRODUCTS)) / 2;
export const TABLETS_PRODUCT_SIZE = 360;
